### ISSUE TITLE
Translate Pending-Export Deletion DN to Human Readable

### ISSUE THREAD

**Issue by TedB-MSFT** [FIMTooler/csReporter#1]
When I use this tool to view pending export deletions I am still seeing only a DN that is in UTF8Hex. Is there a way to convert this to a human readable value or otherwise.

**Comment by FIMTooler** [comment]
Sorry for the delayed response, apparently I didn't get email notification or it went to junk folder.

The value is very likely that way inside the XML file generated by the csexport.exe tool, i.e. it's stored that way in Sync database.  Quick and dirty solution would be to use the CSV output file, run it through a PowerShell script to convert values in that column.

For me to consider adding that feature with a checkbox or something, I'd need sample of entire CSObject from the XML file to examine and test with.

**Comment by FIMTooler** [comment]
No response with example from creator. Closing.
