### ISSUE TITLE
Multivalued Attributes Null Reference Exception on add

### ISSUE THREAD

**Issue by GitBoruta** [FIMTooler/csReporter#2]
Guys, thanks a lot for great job!

I'll keep it quick, in frmFilter.cs file in AddAttribToReportCSV method, there's a failed if condition in line 2567
if (!**_syncdAttrib_**.Multivalued || (**_syncdAttrib_**.Multivalued && report.MvFullList))

This condition is impossible as it's inside and elseif condition where syncdAttrib is null
else if (**_syncdAttrib_ == null** && attribute != null)
{
    if (ADdata && knownADattribs.Contains(attribute.Name))
    {
        strOutput.Append("," + attribute.ADStringValues[0]);
    }
    else
    {
        if (!**_attribute_**.Multivalued || (**_attribute_**.Multivalued && report.MvFullList))
Please change this line to **_attribute_** instead of **_syncdAttrib_** and then it works like a charm :)

**Comment by FIMTooler** [comment]
Good catch! Must have been a copy\paste issue as there's similar IF statements in same function, but also multiple versions of the function for each report type.

Changes has been made and this is now resolved.
